/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<
      'index',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    'admin-announcements': RouteRecordInfo<
      'admin-announcements',
      '/admin/announcements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-application-detail': RouteRecordInfo<
      'admin-application-detail',
      '/admin/application-detail/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-applications': RouteRecordInfo<
      'admin-applications',
      '/admin/applications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-create-worker': RouteRecordInfo<
      'admin-create-worker',
      '/admin/create-worker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-dashboard': RouteRecordInfo<
      'admin-dashboard',
      '/admin/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/data-center': RouteRecordInfo<
      '/admin/data-center',
      '/admin/data-center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-users': RouteRecordInfo<
      'admin-users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-workers': RouteRecordInfo<
      'admin-workers',
      '/admin/workers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'announcement-detail': RouteRecordInfo<
      'announcement-detail',
      '/announcement/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'forgot-password': RouteRecordInfo<
      'forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-book': RouteRecordInfo<
      'order-book',
      '/order/book',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-list': RouteRecordInfo<
      'order-list',
      '/order/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'order-review': RouteRecordInfo<
      'order-review',
      '/order/review/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'register': RouteRecordInfo<
      'register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reload': RouteRecordInfo<
      'reload',
      '/reload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user-center': RouteRecordInfo<
      'user-center',
      '/user/center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user-profile': RouteRecordInfo<
      'user-profile',
      '/user/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'application-status': RouteRecordInfo<
      'application-status',
      '/worker/application-status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'worker-apply': RouteRecordInfo<
      'worker-apply',
      '/worker/apply',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'worker-center': RouteRecordInfo<
      'worker-center',
      '/worker/center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'worker-detail-page': RouteRecordInfo<
      'worker-detail-page',
      '/worker/detail',
      Record<never, never>,
      Record<never, never>,
      | 'worker-detail'
    >,
    'worker-detail': RouteRecordInfo<
      'worker-detail',
      '/worker/detail/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'worker-list': RouteRecordInfo<
      'worker-list',
      '/worker/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'worker-my-services': RouteRecordInfo<
      'worker-my-services',
      '/worker/my-services',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'worker-orders': RouteRecordInfo<
      'worker-orders',
      '/worker/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'worker-profile-edit': RouteRecordInfo<
      'worker-profile-edit',
      '/worker/profile-edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'worker-reviews': RouteRecordInfo<
      'worker-reviews',
      '/worker/reviews',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'worker-schedule': RouteRecordInfo<
      'worker-schedule',
      '/worker/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | 'index'
      views:
        | never
    }
    'src/views/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/views/admin/announcements.vue': {
      routes:
        | 'admin-announcements'
      views:
        | never
    }
    'src/views/admin/application-detail.[id].vue': {
      routes:
        | 'admin-application-detail'
      views:
        | never
    }
    'src/views/admin/applications.vue': {
      routes:
        | 'admin-applications'
      views:
        | never
    }
    'src/views/admin/create-worker.vue': {
      routes:
        | 'admin-create-worker'
      views:
        | never
    }
    'src/views/admin/dashboard.vue': {
      routes:
        | 'admin-dashboard'
      views:
        | never
    }
    'src/views/admin/data-center.vue': {
      routes:
        | '/admin/data-center'
      views:
        | never
    }
    'src/views/admin/users.vue': {
      routes:
        | 'admin-users'
      views:
        | never
    }
    'src/views/admin/workers.vue': {
      routes:
        | 'admin-workers'
      views:
        | never
    }
    'src/views/announcement/[id].vue': {
      routes:
        | 'announcement-detail'
      views:
        | never
    }
    'src/views/forgot-password.vue': {
      routes:
        | 'forgot-password'
      views:
        | never
    }
    'src/views/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/views/order/book.vue': {
      routes:
        | 'order-book'
      views:
        | never
    }
    'src/views/order/list.vue': {
      routes:
        | 'order-list'
      views:
        | never
    }
    'src/views/order/review/[id].vue': {
      routes:
        | 'order-review'
      views:
        | never
    }
    'src/views/register.vue': {
      routes:
        | 'register'
      views:
        | never
    }
    'src/views/reload.vue': {
      routes:
        | 'reload'
      views:
        | never
    }
    'src/views/user/index.vue': {
      routes:
        | '/user/'
      views:
        | never
    }
    'src/views/user/center.vue': {
      routes:
        | 'user-center'
      views:
        | never
    }
    'src/views/user/profile.vue': {
      routes:
        | 'user-profile'
      views:
        | never
    }
    'src/views/worker/application-status.vue': {
      routes:
        | 'application-status'
      views:
        | never
    }
    'src/views/worker/apply.vue': {
      routes:
        | 'worker-apply'
      views:
        | never
    }
    'src/views/worker/center.vue': {
      routes:
        | 'worker-center'
      views:
        | never
    }
    'src/views/worker/detail.vue': {
      routes:
        | 'worker-detail'
        | 'worker-detail-page'
      views:
        | 'default'
    }
    'src/views/worker/detail/[id].vue': {
      routes:
        | 'worker-detail'
      views:
        | never
    }
    'src/views/worker/list.vue': {
      routes:
        | 'worker-list'
      views:
        | never
    }
    'src/views/worker/my-services.vue': {
      routes:
        | 'worker-my-services'
      views:
        | never
    }
    'src/views/worker/orders.vue': {
      routes:
        | 'worker-orders'
      views:
        | never
    }
    'src/views/worker/profile-edit.vue': {
      routes:
        | 'worker-profile-edit'
      views:
        | never
    }
    'src/views/worker/reviews.vue': {
      routes:
        | 'worker-reviews'
      views:
        | never
    }
    'src/views/worker/schedule.vue': {
      routes:
        | 'worker-schedule'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
